INSERT INTO servicios (serv_nombre) VALUES ('Peluquero/a de mascotas');
INSERT INTO servicios (serv_nombre) VALUES ('Paseador/a de mascotas');
INSERT INTO provincia (prov_nombre_de_provincia) VALUES ('Jujuy');
INSERT INTO provincia (prov_nombre_de_provincia) VALUES ('Salta');
INSERT INTO provincia (prov_nombre_de_provincia) VALUES ('Buenos Aires');
INSERT INTO categorias_productos (nombre_categoria) VALUES ('Ropa');
INSERT INTO categorias_productos (nombre_categoria) VALUES ('Camas y Colchone');
INSERT INTO categorias_productos (nombre_categoria) VALUES ('Mochilas, Bolsos y Transportadores');
INSERT INTO categorias_productos (nombre_categoria) VALUES ('Correas');
INSERT INTO categorias_productos (nombre_categoria) VALUES ('Alimentos');
INSERT INTO categorias_productos (nombre_categoria) VALUES ('Jaulas,Casas,Peceras');